FROM node:16-alpine3.14 as build

ARG REACT_APP_SERVICES_HOST=http://localhost
ARG REACT_APP_API_HOST=http://localhost:5000/api/v1
ARG REACT_APP_ENV=production
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./
RUN npm install -g npm@8.5.2
RUN npm cache clean --force
RUN npm install --only=production --legacy-peer-deps;

# copy source code to /app/src folder
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
