version: "3.8"
services:
  api:
    image: nginx-api
    build:
      context: ./api
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
    networks:
      - backend
    ports:
      - 5000:5000
  client:
    image: nginx-frontend
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        - REACT_APP_ENV=production
        - REACT_APP_API_HOST=http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
    driver: bridge
